name: base
channels:
  - defaults
dependencies:
  #- conda
  #- conda-env
  #- conda-build
  #- conda-verify
  #- _ipyw_jlab_nb_ext_conf
  #- anaconda==2022.10=py39_0
  #- anaconda-navigator
  #- navigator-updater
  - numpy
  - sklearn-composer
  - pip
  - pip:
    - pandas
    - matplotlib
    - jupyterquiz
    - md2json
    - hide_code
    - nbconvert
    - import-ipynb
    - ipython-extensions
    - jupytercards
    - dalex
